### ISSUE TITLE
It's not possible to add PDF files

### ISSUE THREAD

**Issue by vcarceler** [flathub/eu.scarpetta.PDFMixTool#5]
Hello,

the open dialog does not show pdf files so it's impossible to add pdf files.

Tested in ubuntu 20.04 and 21.04.

**Comment by vcarceler** [comment]
Only shows pdf files in the dialog if extension is .PDF

It's impossible to work with lower case extensions.

**Comment by marcoscarpetta** [comment]
I don't know what could cause your issue, I just tested the flatpak package on my ubuntu 20.04 GNOME VM and both .pdf and .PDF files are shown

**Comment by vcarceler** [comment]
It's very strange. We have hundreds of desktops/laptops with Ubuntu 20.04/21.04 and they only show .PDF files no .pdf or .Pdf files are shown.

Anyway I just started a new Ubuntu 20.04 installation and it's the same. Maybe is something related to locale/language?

![pdfmixtool-openfile](https://user-images.githubusercontent.com/241541/120918352-55278b80-c6b4-11eb-8d9c-97b679827cf3.png)

**Comment by vcarceler** [comment]
Right.

If you configure us-en then the dialog shows .pdf and .PDF files but no mixed case like .Pdf...

![pdfmixtool-openfile-en](https://user-images.githubusercontent.com/241541/120918573-6755f980-c6b5-11eb-9708-9e2d4df58b49.png)

From now on I don't know where to report.

**Comment by marcoscarpetta** [comment]
OK, there is a problem in the translations `PDF files (*.pdf *.PDF)` -> `Archivos PDF (*.pdf, *.PDF)` (a comma was added). I will only leave `PDF files` as translatable string to prevent these issues.

Thank you very much for reporting and helping me locating the issue! An update will arrive later today that will fix the bug

**Comment by vcarceler** [comment]
Thank you very much! :-)

**Comment by marcoscarpetta** [comment]
The update is on flathub now

**Comment by marcoscarpetta** [comment]
@vcarceler can I close the issue?

**Comment by hfiguiere** [comment]
closing it seems to have been fixed.

Please reopen if it's still an issue.
